### ISSUE TITLE
Issues in the submitted 1.0.0 package

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/vulkan-meta#5]
While reviewing the submitted 1.0.0 package I've noticed the following issues:

1. The project name in `manifest` is `vulkan-meta` instead of `libvulkan-meta`. Unless there is a good reason to deviate, we make it the same as the git project/repository name.

2. In `smoke_test/buildfile` there is stray `testscript{**}`.

I am going to hold off on publishing this package until we finilize (1).

**Comment by Rookfighter** [comment]
Thanks for the review and sorry for the late reply. About point 1. and also considering the same issue in `libopengl-meta`, I would prefer to just rename the repos without lib prefix. I know this might break links from other projects (e.g. imgui), but a) GitHub will maintain a redirection after a rename and b) I will fix that link then.
Any objections?

I will of course fix 2.

**Comment by boris-kolpackov** [comment]
> I would prefer to just rename the repos without lib prefix.

In the end it's your choice, but to me this seems backwards: the main entity here is ` libvulkan-meta` so calling the repository something else just seems like unnecessary variability. In fact, looking at the current state of the repository, there is no need for it to have `libvulkan-meta` as a package and if you were to get rid of this gratuitous structure, then you would have no choice but to use `libvulkan-meta` as the repository name. (I realize that you will likely to add a tests or examples package to it, but, still, this feels like an "implementation detail" that shouldn't affect the name of the repository).

**Comment by Rookfighter** [comment]
Fixed all mentioned issues.
